name: Automated Secret Rotation

on:
  schedule:
    # Run every 90 days at 2 AM UTC
    - cron: '0 2 */90 * *'
  workflow_dispatch:
    inputs:
      rotate_jwt:
        description: 'Rotate JWT Secret'
        required: false
        default: true
        type: boolean
      rotate_database:
        description: 'Rotate Database Password'
        required: false
        default: true
        type: boolean

env:
  AZURE_RESOURCE_GROUP: smart-expense-tracker-rg
  AZURE_KEYVAULT_NAME: ${{ secrets.AZURE_KEYVAULT_NAME }}
  POSTGRES_SERVER_NAME: smart-expense-tracker-db

jobs:
  rotate-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install PowerShell
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Rotate Secrets
      shell: pwsh
      run: |
        $rotateJWT = ${{ github.event.inputs.rotate_jwt || 'true' }}
        $rotateDB = ${{ github.event.inputs.rotate_database || 'true' }}
        
        ./scripts/rotate-secrets.ps1 `
          -KeyVaultName "$env:AZURE_KEYVAULT_NAME" `
          -ResourceGroupName "$env:AZURE_RESOURCE_GROUP" `
          -PostgresServerName "$env:POSTGRES_SERVER_NAME" `
          -RotateJWT:$$rotateJWT `
          -RotateDatabase:$$rotateDB

    - name: Restart App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: smart-expense-tracker-api
        restart: true

    - name: Create GitHub Issue on Failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 Automated Secret Rotation Failed',
            body: `
            ## Secret Rotation Failure
            
            The automated secret rotation workflow failed on ${new Date().toISOString()}.
            
            **Details:**
            - Workflow: ${context.workflow}
            - Run ID: ${context.runId}
            - Repository: ${context.repo.owner}/${context.repo.repo}
            
            **Action Required:**
            Please check the workflow logs and manually rotate secrets if necessary.
            
            **Resources:**
            - Key Vault: ${process.env.AZURE_KEYVAULT_NAME}
            - Resource Group: ${process.env.AZURE_RESOURCE_GROUP}
            `,
            labels: ['security', 'urgent', 'automation']
          })

    - name: Send Teams Notification
      if: always()
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
        title: Secret Rotation Status
        summary: |
          🔐 Automated secret rotation completed
          Status: ${{ job.status }}
          Key Vault: ${{ env.AZURE_KEYVAULT_NAME }}
          Timestamp: ${{ github.event.head_commit.timestamp }}